### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by pirelenito** [joelgriffith/navalia#55]
Awesome project!

Does it make sense to support starting Chrome via Docker? It would allow us to use `navalia` to start the same Chrome rendering on both our local machines (using MacOS) and our integration environment (Travis + Linux).

**Comment by joelgriffith** [comment]
Thanks for the kind words! Yeah, Chrome inside docker makes a lot of sense. I've seen a few Dockerfiles floating around that do this, the issue is keeping them running. There's also a lot of other stuff you have to setup in order for it to "just work" (fonts and so forth).

I don't have a great answer at this point other than I'm working on a SaaS product that does all of the above and some more (logging, replay, and so forth). Probably not the answer you're looking for, but hopefully gives you some perspective.

**Comment by joelgriffith** [comment]
FWIW I now have a separate repo for docker here: https://github.com/joelgriffith/browserless
